[project]
name = "fly-in-the-sky"
version = "0.1.0"
description = "Designing an efficient drone routing system that navigates multiple drones through connected zones while minimizing simulation turns and handling movement constraints"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
]
